"""Agregar tipo_pago a Venta

Revision ID: 66f5ac3e45f1
Revises: 
Create Date: 2026-05-06 11:31:34.237774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f5ac3e45f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_pago', sa.String(length=20), nullable=False, server_default='efectivo'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('tipo_pago')

    # ### end Alembic commands ###
